SELECT 
    ROUTINE_NAME, 
    RIGHT(ROUTINE_DEFINITION, len(ROUTINE_DEFINITION) - PATINDEX(N'%CREATE PROCEDURE %', ROUTINE_DEFINITION)+1) [SQL], 
    LAST_ALTERED 

FROM INFORMATION_SCHEMA.ROUTINES 

WHERE 
        ROUTINE_TYPE = 'PROCEDURE' 
    AND ROUTINE_NAME LIKE N'sp_%' 
    AND ROUTINE_NAME LIKE N'%Revaluation%' 

ORDER BY ROUTINE_NAME; 